### ISSUE TITLE
setuptools support?

### ISSUE THREAD

**Issue by campbellr** [baloo/sphinx-ditaa#3]
Any chance of merging in [ceph/sphinx-ditaa](https://github.com/ceph/sphinx-ditaa), which adds support for installing this package using setuptools?

It would be great if i could use this project simply by running `pip install sphinx-ditaa`

**Comment by daoiqi** [comment]
I want to do it

**Comment by baloo** [comment]
I would accept a PR for it :)

**Comment by baloo** [comment]
Closed by #5
